#logging.pattern.console=%d  -%msg%highlight()%n
#logging.file.name=D:/logs/sells.log
#logging.level.com.ly.LogBackTest=info
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://192.168.2.103/weixinxiaochengxu?characterEncoding=utf-8&useSSL=false
    jpa:
        show-sql: true
    jackson:
        default-property-inclusion: non_null
    freemarker:
        suffix: .ftl
        cache: false
        template-loader-path: classpath:/templates/
    mvc:
        static-path-pattern: /static/**
    web:
        resources:
            static-locations: classpath:/static/
server:
    servlet:
        context-path: /sell